apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres  # Headless service for stable DNS
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        
        env:
        - name: POSTGRES_USER #username
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER

        - name: POSTGRES_PASSWORD #password
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB #database name
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_DB  
        
        
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi